name: Deploy Site
on:
  workflow_call:
    inputs:
      app-name:
        description: App name
        required: true
        type: string
      environment:
        description: Deployment environment
        required: true
        default: 'staging'
        type: string
    secrets:
      AZURE_SUBSCRIPTION_SECRET: 
        required: true

env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ steps.popular-repos-web.outputs.webapp-url }} # Does this output even work? probably need an input map
    needs: build
    concurrency: ${{ inputs.environment }}
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - name: Create deployment slot
      if: github.event_name == 'pull_request'
      run: |
        az webapp deployment slot create --name popular-repos --resource-group pied-piper-inc --slot review-pr-${{ github.event.number }} --configuration-source popular-repos

    - name: Deploy popular repos
      uses: azure/webapps-deploy@v2
      id: popular-repos-web
      with:
        app-name: ${{ inputs.app-name }}
        images: '${{ secrets.AZURE_REGISTRY_NAME }}/popular-repos:${{ env.SHA }}'
        slot-name: ${{ review-pr-${{ github.event.number }} || staging }}